import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Database schema for reFrame.ai (Drizzle ORM + PostgreSQL).
 *
 * The database is not wired up yet: `DATABASE_URL` (see `.env.example`) points
 * at a Postgres instance once one is provisioned, and a `drizzle.config.ts`
 * plus a driver (`pg`/`postgres`) still need to be added before migrations can
 * run. This module is intentionally driver-free so it can be imported by both
 * the migration tooling and any server code that reads or writes rows.
 */

/**
 * One row per completed restyle: who made it, what went in, what came out, and
 * which style/model produced it. Written by `POST /api/generate` once the
 * style engine returns a result image.
 */
export const generations = pgTable("generations", {
  /** Surrogate key. Generated by the database via `gen_random_uuid()`. */
  id: uuid("id").primaryKey().defaultRandom(),
  /** Clerk user id of the account that requested the render. */
  clerkUserId: text("clerk_user_id").notNull(),
  /** Original upload's filename, kept for display. Absent for non-file sources. */
  originalFileName: text("original_file_name"),
  /** URL of the source image that was uploaded. */
  sourceImageUrl: text("source_image_url").notNull(),
  /** URL of the styled result image returned by the engine. */
  resultImageUrl: text("result_image_url").notNull(),
  /** Stable id of the preset used, e.g. `storybook-3d` (`StudioPresetId`). */
  styleSlug: text("style_slug").notNull(),
  /** Human-readable preset label, denormalised for history rendering. */
  styleLabel: text("style_label").notNull(),
  /** Identifier of the model that produced the render. */
  model: text("model").notNull(),
  /** Prompt sent to the model for this render. */
  promptUsed: text("prompt_used").notNull(),
  /** When the row was inserted. */
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/** A row as read back from the `generations` table. */
export type Generation = typeof generations.$inferSelect;

/** A row shaped for insertion into the `generations` table. */
export type NewGeneration = typeof generations.$inferInsert;

