import { index, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

/**
 * Database schema for reFrame.ai (Drizzle ORM + PostgreSQL).
 *
 * The database is not wired up yet: `DATABASE_URL` (see `.env.example`) points
 * at a Postgres instance once one is provisioned, and a `drizzle.config.ts`
 * plus a driver (`pg`/`postgres`) still need to be added before migrations can
 * run. This module is intentionally driver-free so it can be imported by both
 * the migration tooling and any server code that reads or writes rows.
 */

/**
 * One generation request: who asked for it, which preset and model were used,
 * its lifecycle status, and where the finished image lives. A row is written as
 * `pending` before the engine runs and updated to `done` or `failed` afterwards,
 * which lets the monthly quota count in-flight and completed renders.
 */
export const generations = pgTable(
  "generations",
  {
    /** Surrogate key. Generated by the database via `gen_random_uuid()`. */
    id: uuid("id").primaryKey().defaultRandom(),
    /** Clerk user id of the account that requested the render. */
    userId: text("user_id").notNull(),
    /** Stable id of the preset used, e.g. `storybook-3d` (`StudioPresetId`). */
    presetId: text("preset_id").notNull(),
    /** Human-readable preset label, denormalised for history rendering. */
    presetLabel: text("preset_label").notNull(),
    /** Lifecycle state: `pending` | `done` | `failed`. */
    status: text("status").notNull(),
    /** URL of the finished image (ImageKit), or null while pending/failed. */
    imageUrl: text("image_url"),
    /** ImageKit file id, so the file can be deleted together with the row. */
    imageKitFileId: text("image_kit_file_id"),
    /** Identifier of the model that produced the render. */
    model: text("model").notNull(),
    /** How long the engine took, in milliseconds. */
    durationMs: integer("duration_ms"),
    /** When the row was inserted. */
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    /** History and quota queries both scope by user and order by recency. */
    index("generations_user_id_created_at_idx").on(table.userId, table.createdAt),
  ],
);

/** Lifecycle state of a `generations` row. */
export type GenerationStatus = "pending" | "done" | "failed";

/** A row as read back from the `generations` table. */
export type Generation = typeof generations.$inferSelect;

/** A row shaped for insertion into the `generations` table. */
export type NewGeneration = typeof generations.$inferInsert;

